Repository wwcodecolorado/scrollodex, pull requests merged in 2021-10, with the labels that each got.

#81 Added pizzazz to Parastou's card
  src/cards/parastouCard/parastouCard.scss
Labels: hacktoberfest-accepted

#77 Issue76/remove example card
  .github/PULL_REQUEST_TEMPLATE.md
  src/cardsDisplay.jsx
Labels: enhancement, Hacktoberfest

#82 Issue16/multi add name to credits
  CREDITS.md
Labels: Hacktoberfest, hacktoberfest-accepted

#83 Creating simple header issue #2
  public/WWCBD.png
  public/WWCode_Progress_Pride_Logo_Black.png
  src/App.js
  src/Components/Header.jsx
  src/Components/Header.scss
Labels: hacktoberfest-accepted

#84 Issue4/Add my card
  src/cards/audreasCard/audreaCard.jsx
  src/cards/audreasCard/audreaCard.scss
  src/cards/audreasCard/audrea_headshot.jpg
  src/cardsDisplay.jsx
Labels: hacktoberfest-accepted

#85 Issue16/Add name to credits
  CREDITS.md
Labels: hacktoberfest-accepted

#86 Refactor contributor key
  src/Components/Card.jsx
  src/cardsDisplay.jsx
Labels: hacktoberfest-accepted

#87 Added Ada Lovelace card
  src/cards/lovelaceCard/LovelaceCard.jsx
  src/cards/lovelaceCard/lovelace.png
  src/cards/lovelaceCard/lovelaceCard.scss
  src/cardsDisplay.jsx
Labels: hacktoberfest-accepted

#70 Mj/card sorting
  src/cardsDisplay.jsx
Labels: hacktoberfest-accepted
